### PR TITLE
Use environment to pass IB credentials

### PR DESCRIPTION
**Pull request by creack**

### CODE REVIEW

**Comment by uwe** [comment]
The env change looks fine to me. I could not test it (get lots of error messages for "make test" on Mac OS).

I really like the other refactoring with the WriteMap. It is more compact and does not look so tedious.

**Comment by creack** [comment]
Yeah, there are couple of test failing for a while. I'll try to fix them when I got the time.

**Comment by creack** [comment]
btw, `make test` relies on Docker. If you don't want to use Docker, you still can start the tests the old way like travis does.

**Comment by uwe** [comment]
I love docker and boot2docker is working properly on my machine. If they are failing for a while I can also have a look at them.

**Pull request merged**
